Repository blocketGame/Blocket, pull requests merged in 2022-03, with the labels that each got.

#53 Wizardry
  Game-Blocket/Assets/ItemFollowing.cs
  Game-Blocket/Assets/ItemFollowing.cs.meta
  Game-Blocket/Assets/Prefabs/Assets.prefab
  Game-Blocket/Assets/Prefabs/Player.prefab
  Game-Blocket/Assets/Scripts/DataStorage/Profile.cs
  Game-Blocket/Assets/Scripts/Management/Console/Consolehandler.cs
  Game-Blocket/Assets/Scripts/Player/Inventory.cs
  Game-Blocket/Assets/Scripts/Player/Movement.cs
  Game-Blocket/Assets/Scripts/Player/PlayerInteraction.cs
  Game-Blocket/UserSettings/EditorUserSettings.asset
Labels: bug, enhancement

#54 Make world not laggy again
  Game-Blocket/Assets/Prefabs/Assets.prefab
  Game-Blocket/Assets/Scripts/Entities/MobEntities/MobHandler.cs
  Game-Blocket/Assets/Scripts/Management/Console/Consolehandler.cs
  Game-Blocket/Assets/Scripts/Structure/StructureAssets.cs
  Game-Blocket/Assets/Scripts/Terrain/ClientTerrainHandler.cs
  Game-Blocket/Assets/Scripts/Terrain/ServerTerrainHandler.cs
  Game-Blocket/ProjectSettings/UnityConnectSettings.asset
Labels: bugfix

#56 Alpha 1.6
  Game-Blocket/Assets/ItemFollowing.cs
  Game-Blocket/Assets/ItemFollowing.cs.meta
  Game-Blocket/Assets/Prefabs/Assets.prefab
  Game-Blocket/Assets/Prefabs/Player.prefab
  Game-Blocket/Assets/Scripts/DataStorage/Profile.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/MobHandler.cs
  Game-Blocket/Assets/Scripts/Management/Console/Consolehandler.cs
  Game-Blocket/Assets/Scripts/Player/Inventory.cs
  Game-Blocket/Assets/Scripts/Player/Movement.cs
  Game-Blocket/Assets/Scripts/Player/PlayerInteraction.cs
  Game-Blocket/Assets/Scripts/Structure/StructureAssets.cs
  Game-Blocket/Assets/Scripts/Terrain/ClientTerrainHandler.cs
  Game-Blocket/Assets/Scripts/Terrain/ServerTerrainHandler.cs
  Game-Blocket/Assets/Scripts/UI/MainGame/UIInventory.cs
  Game-Blocket/ProjectSettings/UnityConnectSettings.asset
  Game-Blocket/UserSettings/EditorUserSettings.asset
Labels: enhancement, bugfix

#66 Feature/Singelton Structure
  .gitignore
  Game-Blocket/Assets/Scenes/Lobby.unity
  Game-Blocket/Assets/Scripts/Camera/FluentCameraBehaviour.cs
  Game-Blocket/Assets/Scripts/Camera/MoveBackgroundWithPlayer.cs
  Game-Blocket/Assets/Scripts/Camera/SmoothCamera.cs
  Game-Blocket/Assets/Scripts/DataStorage/AssetIO.cs
  Game-Blocket/Assets/Scripts/DataStorage/PlayerProfile.cs
  Game-Blocket/Assets/Scripts/DataStorage/PrefabAssets.cs
  Game-Blocket/Assets/Scripts/DataStorage/WorldProfile.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/Enemies/EnemieSpawner.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/Enemies/SkeletonLogic.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/Enemies/ZombieBrain.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/MobAssets.cs
  Game-Blocket/Assets/Scripts/Entities/MobEntities/MobHandler.cs
  Game-Blocket/Assets/Scripts/ItemHandling/Crafting/CraftingHandler.cs
  Game-Blocket/Assets/Scripts/ItemHandling/Crafting/CraftingRecipe.cs
  Game-Blocket/Assets/Scripts/ItemHandling/Crafting/CraftingStation.cs
  Game-Blocket/Assets/Scripts/ItemHandling/Item.cs
  Game-Blocket/Assets/Scripts/ItemHandling/ItemAssets.cs
  Game-Blocket/Assets/Scripts/Light/ClockHandler.cs
  Game-Blocket/Assets/Scripts/Light/ClockHandler.cs.meta
  Game-Blocket/Assets/Scripts/Light/DayNightCycle.cs
  Game-Blocket/Assets/Scripts/Light/LightScript.cs
  Game-Blocket/Assets/Scripts/Management/Console/ConsoleEntry.cs
  Game-Blocket/Assets/Scripts/Management/Console/Consolehandler.cs
  Game-Blocket/Assets/Scripts/Management/GameManager.cs
  Game-Blocket/Assets/Scripts/Management/GlobalVariables.cs
  Game-Blocket/Assets/Scripts/Management/NetworkVariables.cs
  Game-Blocket/Assets/Scripts/Player/Inventory.cs
  Game-Blocket/Assets/Scripts/Player/ItemFollowing.cs
  Game-Blocket/Assets/Scripts/Player/Movement.cs
  Game-Blocket/Assets/Scripts/Player/PlayerInteraction.cs
  Game-Blocket/Assets/Scripts/Player/PlayerVariables.cs
  Game-Blocket/Assets/Scripts/Structure/Structure.cs
  Game-Blocket/Assets/Scripts/Structure/StructureAssets.cs
  Game-Blocket/Assets/Scripts/Terrain/ClientTerrainHandler.cs
  Game-Blocket/Assets/Scripts/Terrain/Components/NoiseGenerator.cs
  Game-Blocket/Assets/Scripts/Terrain/ServerTerrainHandler.cs
  Game-Blocket/Assets/Scripts/Terrain/TerrainChunk.cs
  Game-Blocket/Assets/Scripts/Terrain/TerrainGeneration.cs
  Game-Blocket/Assets/Scripts/Terrain/TerrainHandler.cs
  Game-Blocket/Assets/Scripts/Terrain/WorldAssets.cs
  Game-Blocket/Assets/Scripts/Terrain/WorldData.cs
  Game-Blocket/Assets/Scripts/UI/Lobby/ListContentUI.cs
  Game-Blocket/Assets/Scripts/UI/Lobby/UILobby.cs
  Game-Blocket/Assets/Scripts/UI/Lobby/UIProfileSite.cs
  Game-Blocket/Assets/Scripts/UI/MainGame/PlayerHealth.cs
  Game-Blocket/Assets/Scripts/UI/MainGame/ShowTimer.cs
  Game-Blocket/Assets/Scripts/UI/MainGame/UIInventory.cs
  Game-Blocket/Assets/Scripts/UI/MainGame/UIInventorySlot.cs
  Game-Blocket/Assets/Scripts/UI/MainManu/UIMainMenu.cs
  Game-Blocket/Assets/Scripts/UI/ScrollViewHandler.cs
Labels: documentation
